/******************************************************************************
 * Copyright 2024 TypeFox GmbH
 * This program and the accompanying materials are made available under the
 * terms of the MIT License, which is available in the project root.
 ******************************************************************************/

import {
    LangiumSharedCoreServices,
    Module,
    PartialLangiumCoreServices,
    createDefaultCoreModule,
    inject,
} from "langium";
import {
    DefaultSharedModuleContext,
    LangiumServices,
    LangiumSharedServices,
    createDefaultSharedModule,
} from "langium/lsp";
import {
    TypirLangiumServices,
    createTypirLangiumServices,
    initializeLangiumTypirServices,
} from "typir-langium";
import { LoxAstType, reflection } from "./generated/ast.js";
import {
    LoxGeneratedModule,
    LoxGeneratedSharedModule,
} from "./generated/module.js";
import { LoxLinker } from "./lox-linker.js";
import { LoxScopeProvider } from "./lox-scope.js";
import { LoxTypeSystem } from "./lox-type-checking.js";
import { LoxValidationRegistry, LoxValidator } from "./lox-validator.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type LoxAddedServices = {
    validation: {
        LoxValidator: LoxValidator;
    };
    typir: TypirLangiumServices<LoxAstType>; // all Langium services are able to access these Typir services for type-checking
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type LoxServices = LangiumServices & LoxAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export function createLoxModule(
    shared: LangiumSharedCoreServices,
): Module<LoxServices, PartialLangiumCoreServices & LoxAddedServices> {
    return {
        validation: {
            ValidationRegistry: (services) =>
                new LoxValidationRegistry(services),
            LoxValidator: () => new LoxValidator(),
        },
        // For type checking with Typir, configure the Typir & Typir-Langium services in this way:
        typir: () =>
            createTypirLangiumServices(
                shared,
                reflection,
                new LoxTypeSystem(),
                {
                    /* customize Typir services here */
                },
            ),
        references: {
            ScopeProvider: (services) => new LoxScopeProvider(services),
            Linker: (services) => new LoxLinker(services),
        },
    };
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createLoxServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices;
    Lox: LoxServices;
} {
    const shared = inject(
        createDefaultSharedModule(context),
        LoxGeneratedSharedModule,
    );
    const Lox = inject(
        createDefaultCoreModule({ shared }),
        LoxGeneratedModule,
        createLoxModule(shared),
    );
    shared.ServiceRegistry.register(Lox);
    initializeLangiumTypirServices(Lox, Lox.typir); // initialize the Typir type system once
    return { shared, Lox };
}
