name: Publish API docs

permissions:
  pages: write
  id-token: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    name: Build and publish API docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Build API docs
        run: |
          npm ci
          npm run build
          npm run docs
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
